# Generated by Django 3.2.7 on 2021-10-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='buyer_type',
            field=models.CharField(max_length=11, verbose_name='Тип покупателя'),
        ),
    ]
