# Generated by Django 3.2.7 on 2021-10-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_buyer_purchased_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_type',
            field=models.IntegerField(choices=[(1, 'Частный'), (2, 'Юр. Лицо')], verbose_name='Тип покупателя'),
        ),
    ]
